### ISSUE TITLE
sort buttons still display inside beacon & loom

### ISSUE THREAD

**Issue by ExternalHost0** [Chailotl/inventory-sort#10] opened 2024-05-26 23:19 UTC
As the title states, the sort buttons are not hidden inside the beacon & loom screen when they should be disabled by default (according to the config).

**Comment by Chailotl** [comment] 2024-05-28 01:36
Gah, seems to be a regression bug, thank you for reporting this. Unfortunately I won't be able to fix this until I return from vacation in a week, so sit tight!

**Comment by Chailotl** [comment] 2024-08-17 22:27
Fixed in eaae859e0b25d60105867908466a033900745ab4

**Closed by Chailotl** 2024-08-17 22:27 UTC
